### PR TITLE
Update ch03

### PR DESCRIPTION
**Pull request by ohtaman**
1. Sort import statements
2. Change keras to tensorflow.keras
    - Currentry, original Keras, not tf.keras, is not suitable for TensorFlow 2.0. So we want to use tf.keras everywhere.
3. Add gzip module and remove some code to call zcat
    - I prefer  standard module to external commands. But this change may not be necessary.
4. Add note about a error caused by cache.
   - I'm not English native. Please point out if the grammar is wrong

### CODE REVIEW

**Comment by ohtaman** [comment]
TensorFlow 2.0 and 1.0 are not compatible, so it may be better to have another branch instead of master.
@DOsinga How do you think?

**Comment by DOsinga** [comment]
It would be a good idea to move to 2.0, but yeah, it would need careful testing. It seems you are better at that then I am, so sure, why not. But maybe like you suggest we can put this together in a feature branch that we work on together?

**Comment by DOsinga** [comment]
Any thoughts on how to best progress on this?

**Comment by MarcusFra** [comment]
Dear @DOsinga, are you still planning to update to TensorFlow 2.x? Or do you know any fork for which it was done yet? There are some readers (of the german translation) who ask for.

**Pull request closed without merging**
